Matrix Operations in NumPy

1. Element-wise Addition, Subtraction, and Division

In [5]:
import numpy as np
import math

x = np.array([[1,2], [3,4]])
y = np.array([[5,6], [7,8]])

print("Addition:\n", np.add(x,y))
print("Subtraction:\n", np.subtract(x,y))
print("Division:\n", np.divide(x,y))

Addition:
 [[ 6  8]
 [10 12]]
Subtraction:
 [[-4 -4]
 [-4 -4]]
Division:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [6]:
x = np.array([[1,2], [3,4]])
y = np.array([[5,6], [7,8]])

print("The element wise addition of matrix is:\n",np.add(x,y))
print("The elnet wise subtraction of matrix is:\n",np.subtract(x,y))
print("The element wise division of matrix is:\n",np.divide(x,y))

The element wise addition of matrix is:
 [[ 6  8]
 [10 12]]
The elnet wise subtraction of matrix is:
 [[-4 -4]
 [-4 -4]]
The element wise division of matrix is:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


2. Element-wise Multiplication vs. Matrix Multiplication

In [8]:
#dot() : - Multipy elements of a row from first array with elements of a colums from the second array, and then add together .
import numpy as np

x = np.array([[1,2], [4,5]])
y = np.array([[7,8], [9,10]])

print("Element-wise multiplication:\n", np.multiply(x,y))
print("Matrix multiplication:\n", np.dot(x,y))

Element-wise multiplication:
 [[ 7 16]
 [36 50]]
Matrix multiplication:
 [[25 28]
 [73 82]]


In [9]:
import numpy as np
 
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])
res = np.mod(a, b)
print(res)

[ 1  2  3 10]


Other Useful NumPy Matrix Functions

In [13]:
#axis0 = columns
#axis1 = rows
#Transpose means converting rows into columns and columns into rows.

x = np.array([[1,2], [4,5]])
y = np.array([[7,8], [9,10]])

print("Square root:\n", np.sqrt(x))
print("Sum of all elements:\n", np.sum(y))

print("Column wise sum:", np.sum(y, axis=0))
print("Row wise sum:", np.sum(y, axis=1))
print("Transpose:\n", x.T)

Square root:
 [[1.         1.41421356]
 [2.         2.23606798]]
Sum of all elements:
 34
Column wise sum: [16 18]
Row wise sum: [15 19]
Transpose:
 [[1 4]
 [2 5]]


Products of Vectors and Matrices in NumPy

In [17]:
a = np.array([2,6])
b = np.array([3,10])

print("Inner product of vectors a and b =")
print(np.inner(a,b))

x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])

print("Inner product of vectors x and y =")
print(np.inner(x,y))

Inner product of vectors a and b =
66
Inner product of vectors x and y =
[[17 52]
 [13 62]]


In [18]:
a = np.array([2,6])
b = np.array([3,10])

print("Outer product of vectors a and b =")
print(np.outer(a,b))

x = np.array([[3, 6, 4], [9, 4, 6]])
y = np.array([[1, 15, 7], [3, 10, 8]])

print("Outer product of matrices x and y =")
print(np.outer(x,y))

Outer product of vectors a and b =
[[ 6 20]
 [18 60]]
Outer product of matrices x and y =
[[  3  45  21   9  30  24]
 [  6  90  42  18  60  48]
 [  4  60  28  12  40  32]
 [  9 135  63  27  90  72]
 [  4  60  28  12  40  32]
 [  6  90  42  18  60  48]]


Exponentiation (Power)

In [19]:
import numpy as np
 
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])
res = np.power(a, b)
print(res)

[        25 1934917632  419538377          0]


Cross Product

In [20]:
import numpy as np
#(a2​b3​−a3​b2​,a3​b1​−a1​b3​,a1​b2​−a2​b1​)
# Define vectors as 3D (z=0 for 2D compatibility)
a = np.array([3, 6, 0])
b = np.array([9, 10, 0])

print("Cross product of vectors a and b =")
print(np.cross(a, b))

# Define matrices (already 3D rows)
x = np.array([[2, 6, 9], [2, 7, 3]])
y = np.array([[7, 5, 6], [3, 12, 3]])

print("Cross product of matrices x and y =")
print(np.cross(x, y))

Cross product of vectors a and b =
[  0   0 -24]
Cross product of matrices x and y =
[[ -9  51 -32]
 [-15   3   3]]


Numpy numpy.resize() - Python

In [22]:
arr = np.array([1, 2, 3, 4, 5, 6,])
arr.resize((2, 3))
print(arr)
      

[[1 2 3]
 [4 5 6]]


In [23]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr.resize((3, 4))
print(arr)

[[1 2 3 4]
 [5 6 0 0]
 [0 0 0 0]]


In [24]:
arr = np.array([10, 20, 30, 40, 50])
arr.resize((2,2))
print(arr)

[[10 20]
 [30 40]]


Aggregation Functions (sum, mean, max, min)

In [25]:
arr = np.array([5, 10, 15])
print(np.sum(arr))

30


In [27]:
a = 10
b = 21
print(np.maximum(a, b))

21


In [28]:
arr = [20, 2, 7, 1, 34] # n/5
res = np.mean(arr)
print(res)

12.8


In [29]:
arr = [[14, 7, 12],
       [15, 6, 72],
       [23, 2, 54]]

print(np.mean(arr))
print(np.mean(arr, axis = 0))
print(np.mean(arr, axis = 1))

22.77777777777778
[17.33333333  5.         46.        ]
[11.         31.         26.33333333]


In [31]:
a = 10 
b = 21
print(np.minimum(a, b))

10


In [32]:
a = np.array([np.nan, 0 , np.nan])
b = np.array([np.nan, np.nan, 0])
print(np.minimum(a, b))

[nan nan nan]


In [33]:
a = np.array([[4, 7, 8], [1, 5, 8]])
b = np.array([3, 6, 10])
print(np.minimum(a, b))

[[3 6 8]
 [1 5 8]]


Reshape NumPy Array - Python

In [34]:
a = np.array([1, 2, 3, 4, 5, 6])
r = a.reshape(2,3)
print(r)

[[1 2 3]
 [4 5 6]]


In [36]:
a = np.array([1, 2, 3, 4, 5,  6, 7, 8])
r = a.reshape(2, 2, 2)
print(r)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [37]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
r = a.reshape(3, -1)
print(r)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Stacking

In [38]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
res = np.stack((a,b), axis = 0)
print(res)

[[1 2 3]
 [4 5 6]]


In [39]:
#This example shows how stacking the same 1D arrays along axis 0, 1, and -1 changes the output shape.
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.stack((a,b), axis = 0))
print(np.stack((a,b), axis = 1))
print(np.stack((a,b), axis = -1))

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]


In [40]:
#This example stacks two 2D arrays along axis 0, 1, and 2 to show how the new 3D structure changes.
x = np.array([[1, 2, 3],
              [4, 5, 6]])

y = np.array([[7, 8, 9],
              [10, 11, 12]])

print(np.stack((x,y), axis=0))
print(np.stack((x,y), axis=1))
print(np.stack((x,y), axis=2))

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[[ 1  2  3]
  [ 7  8  9]]

 [[ 4  5  6]
  [10 11 12]]]
[[[ 1  7]
  [ 2  8]
  [ 3  9]]

 [[ 4 10]
  [ 5 11]
  [ 6 12]]]


In [41]:
#This example stacks two 3D arrays along axis 0, 1, 2, and 3 to demonstrate how stacking works with higher-dimension data.
import numpy as np

m = np.array([[[1, 2], [3, 4]],
              [[5, 6], [7, 8]]])

n = np.array([[[10, 20], [30, 40]],
              [[50, 60], [70, 80]]])

print(np.stack((m, n), axis=0))
print(np.stack((m, n), axis=1))
print(np.stack((m, n), axis=2))
print(np.stack((m, n), axis=3))

[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[10 20]
   [30 40]]

  [[50 60]
   [70 80]]]]
[[[[ 1  2]
   [ 3  4]]

  [[10 20]
   [30 40]]]


 [[[ 5  6]
   [ 7  8]]

  [[50 60]
   [70 80]]]]
[[[[ 1  2]
   [10 20]]

  [[ 3  4]
   [30 40]]]


 [[[ 5  6]
   [50 60]]

  [[ 7  8]
   [70 80]]]]
[[[[ 1 10]
   [ 2 20]]

  [[ 3 30]
   [ 4 40]]]


 [[[ 5 50]
   [ 6 60]]

  [[ 7 70]
   [ 8 80]]]]


Splitting Arrays

In [42]:
arr = np.array([1, 2, 3, 4, 5, 6])
res = np.array_split(arr, 3)
print(res)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [43]:
arr = np.arange(6)
res = np.split(arr, 2)
print(res)

[array([0, 1, 2]), array([3, 4, 5])]


In [44]:
arr = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9],[10, 11, 12]])
res = np.vsplit(arr,2)
print(res)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]])]


In [45]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
res = np.hsplit(arr, 2)
print(res)

[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12]])]


In [46]:
import numpy as np

arr = np.arange(24).reshape((2, 3, 4))
res = np.dsplit(arr, 2)
print(res)

[array([[[ 0,  1],
        [ 4,  5],
        [ 8,  9]],

       [[12, 13],
        [16, 17],
        [20, 21]]]), array([[[ 2,  3],
        [ 6,  7],
        [10, 11]],

       [[14, 15],
        [18, 19],
        [22, 23]]])]


Broadcasting

In [47]:
a = np.array([[1, 2, 3], [4, 5, 6]])
x = 10
print(a+x)

[[11 12 13]
 [14 15 16]]


Broadcasting in Conditional Operations

In [49]:
a = np.array([12, 24, 35, 45, 60, 72])
b = np.array(["adult", "Minor"])
res = np.where(a>18, b[0], b[1])
print(res)

['Minor' 'adult' 'adult' 'adult' 'adult' 'adult']


Using Broadcasting for Matrix Multiplication

In [50]:
m = np.array([[1,2], [3,4]])
v = np.array([10, 20])
res = m*v
print(res)

[[10 40]
 [30 80]]
