In [2]:
import numpy as np

In [3]:
rand(2)

NameError: name 'rand' is not defined

In [ ]:
random.rand(2)

In [ ]:
np.random.rand(2)

In [ ]:
np.random.rand(3)

In [ ]:
np.random.rand(2,3)

In [ ]:
np.random.randint(3)

In [ ]:
np.random.randint(2,10)

In [ ]:
np.random.randint(2,10,4)

In [ ]:
np.random.randint(-30,20,10)

In [13]:
np.random.randint(10,40,(10,10))

array([[24, 31, 12, 29, 33, 27, 17, 39, 30, 23],
       [32, 28, 15, 17, 38, 17, 14, 29, 19, 38],
       [23, 11, 21, 33, 33, 31, 32, 24, 33, 33],
       [22, 12, 31, 22, 13, 15, 15, 17, 14, 37],
       [26, 34, 12, 11, 31, 34, 17, 12, 25, 35],
       [33, 13, 21, 10, 14, 17, 17, 20, 30, 18],
       [30, 37, 17, 22, 12, 32, 23, 15, 19, 32],
       [13, 21, 21, 12, 29, 10, 14, 12, 26, 21],
       [33, 29, 32, 13, 11, 34, 17, 26, 24, 17],
       [39, 19, 13, 17, 32, 28, 22, 38, 18, 17]])

In [10]:
np.random.rand(2,3)

array([[0.96897163, 0.7643561 , 0.97361372],
       [0.95443544, 0.67622286, 0.77768131]])

In [12]:
np.random.randint(2,3,3)

array([2, 2, 2])

In [14]:
arr

NameError: name 'arr' is not defined

In [19]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [20]:
type(my_list)

list

In [21]:
arr = np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [22]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [23]:
arr.reshape(3,3)

ValueError: cannot reshape array of size 6 into shape (3,3)

In [24]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [25]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

# slicing in matrix

In [26]:
b = np.random.randint(10,20,(15,4))
b

array([[13, 12, 18, 15],
       [11, 15, 12, 12],
       [10, 16, 10, 18],
       [18, 11, 19, 19],
       [12, 14, 16, 13],
       [18, 19, 13, 19],
       [14, 10, 12, 11],
       [14, 19, 10, 13],
       [12, 11, 10, 11],
       [14, 19, 12, 17],
       [18, 15, 15, 12],
       [17, 19, 15, 17],
       [13, 14, 10, 13],
       [15, 15, 15, 13],
       [19, 10, 12, 15]])

In [27]:
type(b)

numpy.ndarray

In [28]:
b[:]

array([[13, 12, 18, 15],
       [11, 15, 12, 12],
       [10, 16, 10, 18],
       [18, 11, 19, 19],
       [12, 14, 16, 13],
       [18, 19, 13, 19],
       [14, 10, 12, 11],
       [14, 19, 10, 13],
       [12, 11, 10, 11],
       [14, 19, 12, 17],
       [18, 15, 15, 12],
       [17, 19, 15, 17],
       [13, 14, 10, 13],
       [15, 15, 15, 13],
       [19, 10, 12, 15]])

In [29]:
b[1:4]

array([[11, 15, 12, 12],
       [10, 16, 10, 18],
       [18, 11, 19, 19]])

In [31]:
b[-1:]

array([[19, 10, 12, 15]])

In [32]:
b[:-1]

array([[13, 12, 18, 15],
       [11, 15, 12, 12],
       [10, 16, 10, 18],
       [18, 11, 19, 19],
       [12, 14, 16, 13],
       [18, 19, 13, 19],
       [14, 10, 12, 11],
       [14, 19, 10, 13],
       [12, 11, 10, 11],
       [14, 19, 12, 17],
       [18, 15, 15, 12],
       [17, 19, 15, 17],
       [13, 14, 10, 13],
       [15, 15, 15, 13]])

In [33]:
b[-2:]

array([[15, 15, 15, 13],
       [19, 10, 12, 15]])

In [34]:
b

array([[13, 12, 18, 15],
       [11, 15, 12, 12],
       [10, 16, 10, 18],
       [18, 11, 19, 19],
       [12, 14, 16, 13],
       [18, 19, 13, 19],
       [14, 10, 12, 11],
       [14, 19, 10, 13],
       [12, 11, 10, 11],
       [14, 19, 12, 17],
       [18, 15, 15, 12],
       [17, 19, 15, 17],
       [13, 14, 10, 13],
       [15, 15, 15, 13],
       [19, 10, 12, 15]])

In [35]:
b[1:3]

array([[11, 15, 12, 12],
       [10, 16, 10, 18]])

In [38]:
b[1,3]

12

In [40]:
b[2,3]

18

In [41]:
b

array([[13, 12, 18, 15],
       [11, 15, 12, 12],
       [10, 16, 10, 18],
       [18, 11, 19, 19],
       [12, 14, 16, 13],
       [18, 19, 13, 19],
       [14, 10, 12, 11],
       [14, 19, 10, 13],
       [12, 11, 10, 11],
       [14, 19, 12, 17],
       [18, 15, 15, 12],
       [17, 19, 15, 17],
       [13, 14, 10, 13],
       [15, 15, 15, 13],
       [19, 10, 12, 15]])

In [42]:
b[1,3]

12

In [43]:
b[1,-1]

12

#Numpy Opetation

In [46]:
arr

array([0, 1, 2, 3, 4, 5])

In [47]:
arr.max()

5

In [48]:
arr.min()

0

In [51]:
from numpy import * #256 function called internally
a = array([1,2,3,4,9])
median(a)

3.0

Indexing in numpy

In [54]:
mat = np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [55]:
row = 4
col = 5

In [56]:
row

4

In [57]:
col

5

In [58]:
mat[row,col]

45

In [59]:
mat[1] # how to print rows

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [60]:
mat[:,col] # how to print columns from thw matrix

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [61]:
mat[:,3]

array([ 3, 13, 23, 33, 43, 53, 63, 73, 83, 93])

In [62]:
mat[::-1]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [64]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [65]:
mat[::-2]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [67]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [69]:
mat[2:6,2:4]

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [70]:
mat[1:2,2:4]

array([[12, 13]])

In [71]:
mat[3:5,2:4]

array([[32, 33],
       [42, 43]])

# Masking And Filter

In [72]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [73]:
mat>50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [74]:
mat[mat>50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [75]:
mat[mat<=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [76]:
mat[mat!=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])